---
language: node_js
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - "0.10"
before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
install:
- "npm install"
script:
  - npm run-script test
env:
  global:
  - BROCCOLI_ENV="production"
